// <auto-generated />
namespace eDoc.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class baseDbType_and_AppUser_and_PersonalInfo_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(baseDbType_and_AppUser_and_PersonalInfo_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201806241441174_baseDbType_and_AppUser_and_PersonalInfo_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
