// <auto-generated />
namespace eDoc.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AppRole_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppRole_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201806230003074_AppRole_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
