// <auto-generated />
namespace eDoc.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class added_entities___DiseaseComplaint_CommonMedicalRecord : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_entities___DiseaseComplaint_CommonMedicalRecord));
        
        string IMigrationMetadata.Id
        {
            get { return "201806281717144_added_entities___DiseaseComplaint_CommonMedicalRecord"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
